feat: add support to iterator over encrypted zip
OSSystems/compress-tools-rs pull request #116
Opened 2023-05-31 12:06 UTC by hivexdev

Adding support to iterate over encrypted archives zip.

ONLY SUPPORTS ZIP ( libarchive limitation ) 
[libarchive documentation -> readme.md](https://github.com/libarchive/libarchive)

![Screenshot from 2023-05-31 09-00-18](https://github.com/OSSystems/compress-tools-rs/assets/41262469/1ccf4fee-efb0-4da9-8926-88b248285040)

Note:
I just implemented it in the iterator, because I don't have time to implement it in the rest, but the idea is the same.

**Support for (RAR)**
It doesn't support encrypted '.rar' files, because it is a limitation of the libarchive itself, I searched in every way and even after implementing the correction I tried to iterate over a '.rar' file, but I don't get an error and it doesn't display any content either.

the only solution I saw that works is a binding made in unrar.c, but for that I would have to restructure the entire library to implement only this use case for '.rar' file

2023-05-31 17:10 UTC, otavio requested changes
Thank you for the pull request! We appreciate your contribution to the project. However, we still have some items to look at before we can merge your code into the repository. I also wanted to let you know that I sent a small code rework to simplify the code. Thank you again for your help!

2023-05-31 18:56 UTC, otavio commented
Also, CI is failing but it works locally; any idea?

2023-06-01 03:27 UTC, hivexdev commented
I didn't understand either, I realized that when I run the "cargo test" it breaks in my test, but if I run my test individually it works, it's like I'm mocking some function I'm using..

And regarding the fixes, I'll try to do it tomorrow, all the points you commented make total sense.

2023-06-01 11:32 UTC, otavio commented
If it fails in your machine, it might be a race of memory corruption. Check in cargo-valgrind.

2023-06-01 11:33 UTC, otavio commented on src/iterator.rs
> +pub struct Password(Vec<u8>);
I renamed, doc is still pending.

2023-06-01 19:37 UTC, otavio commented
@hivexdev progress. The failing tests are fixed. The Windows failure is unrelated.

2023-06-26 20:28 UTC, otavio commented
@hivexdev have you looked at this?

2023-11-27 05:24 UTC, AngelineNinu commented
can the passphrase be non ascii , will this work for decrypting a password protectd zip?

2023-11-27 05:35 UTC, AngelineNinu commented
can non ascii password be used to decrypt a paswd protectd zip file

2026-04-22 20:25 UTC, otavio commented
Superseded by #158, which rebases this work onto current `master`, squashes the fixups, and addresses a few correctness issues (passphrase return code is now checked, `CString` construction no longer panics on NUL bytes, dropped an unsound `*const i8` cast, and `from_read`'s signature is preserved). Original authorship is kept on the commit; thanks for the contribution!

2026-04-22 20:25 UTC, closed without merging